server {
    listen 80;

    server_name _;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    types {
        application/javascript js mjs;
    }

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 1g;

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        text/xml
        application/xml
        application/xml+rss
        text/javascript;
}