sonar.organization=tsl-organisation
sonar.host.url=https://sonarcloud.io
# Change below key for each respective repo
sonar.projectKey=Naveen-Sarvepalli_TSL-Frontend 
sonar.sources=.
sonar.exclusions=node_modules/**
